version: "3.7"
services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  mongo:
    image: mongo:4.0
    ports:
      - 27016:27017
    volumes:
      - mailer:/data/db/
volumes:
  mailer:
